[package]
name = "rrts"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.13.2", features = ["dynamic_linking"] }
bevy-inspector-egui = "0.24.0"
bevy_egui = "0.27.1"
bevy_mod_picking = "0.19.1"
bevy_rts_camera = "0.7.2"
bevy_xpbd_3d = "0.4.2"
